### ISSUE TITLE
jump 0.1.0 breaks on node 0.6.2

### ISSUE THREAD

**Issue by fhemberger** [friggeri/jump#6]
After updating from 0.0.8 to 0.1.0, I get the following error:

```
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object #<ReadStream> has no method 'setRawMode'
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/jump/node_modules/charm/index.js:43:23)
    at /usr/local/lib/node_modules/jump/node_modules/charm/index.js:29:12
    at Object.<anonymous> (/usr/local/lib/node_modules/jump/jump.js:32:34)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)
```

**Comment by friggeri** [comment]
Sorry, I should have specified in package.json that 0.1.0 required node 0.7.7. I don't plan on supporting 0.6.2.

**Comment by fhemberger** [comment]
Can you then please only push the package version of jump to npm which uses the node stable branch?
I use jump on a daily basis (and really love it!), I don't want it to break on `npm update -g` (which is necessary from time to time).
